export const HELP_TEXT =
  'instructions:\n1). Set email address\n\tset-email=[email]\n2). Set subject\n\tset-subject=[subject]\n3).Set message\n\tset-msg=[msg]\n4).send email\n\tsend\n5). Help\n\thelp\nretromailclient>';

export const LOADING_TEXT = [
  '[|] Loading Mail Client...',
  '[/] Loading Mail Client...',
  '[-] Loading Mail Client...',
  '[\\] Loading Mail Client...',
  '[|] Loading Mail Client...',
  '[/] Loading Mail Client...',
  '[-] Loading Mail Client...',
  '[\\] Loading Mail Client...',
  '[|] Loading Mail Client...',
  '[/] Loading Mail Client...',
  '[-] Loading Mail Client...',
  '[\\] Loading Mail Client...',
  '[|] Loading Mail Client...',
  '[/] Loading Mail Client...',
  '[-] Loading Mail Client...',
  '[\\] Loading Mail Client...',
  '[|] Loading Mail Client...',
  '[/] Loading Mail Client...',
  '[-] Loading Mail Client...',
  '[\\] Loading Mail Client...',
  '[|] Loading Mail Client...',
  '[/] Loading Mail Client...',
  '[-] Loading Mail Client...',
  '[\\] Loading Mail Client...',
  '[|] Loading Mail Client...',
  '[/] Loading Mail Client...',
  '[-] Loading Mail Client...',
  '[\\] Loading Mail Client...',
  '[|] Loading Mail Client...',
  '[/] Loading Mail Client...',
  '[-] Loading Mail Client...',
  '[\\] Loading Mail Client...',
  '[|] Loading Mail Client...',
  '[/] Loading Mail Client...',
  '[-] Loading Mail Client...',
  '[\\] Loading Mail Client...',
  '[|] Loading Mail Client...',
  '[/] Loading Mail Client...',
  '[-] Loading Mail Client...',
  '[\\] Loading Mail Client...',
];

export const TERMINAL_DEFAULT_PROMPT = 'retromailclient>';
